// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: ethereal.proto

package wssClient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S             string                 `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	BidPx         string                 `protobuf:"bytes,2,opt,name=bid_px,json=bidPx,proto3" json:"bid_px,omitempty"`
	AskPx         string                 `protobuf:"bytes,3,opt,name=ask_px,json=askPx,proto3" json:"ask_px,omitempty"`
	BidAmt        string                 `protobuf:"bytes,4,opt,name=bid_amt,json=bidAmt,proto3" json:"bid_amt,omitempty"`
	AskAmt        string                 `protobuf:"bytes,5,opt,name=ask_amt,json=askAmt,proto3" json:"ask_amt,omitempty"`
	MarkPx        string                 `protobuf:"bytes,6,opt,name=mark_px,json=markPx,proto3" json:"mark_px,omitempty"`
	Mark24HPx     string                 `protobuf:"bytes,7,opt,name=mark24h_px,json=mark24hPx,proto3" json:"mark24h_px,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketPrice) Reset() {
	*x = MarketPrice{}
	mi := &file_ethereal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketPrice) ProtoMessage() {}

func (x *MarketPrice) ProtoReflect() protoreflect.Message {
	mi := &file_ethereal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketPrice.ProtoReflect.Descriptor instead.
func (*MarketPrice) Descriptor() ([]byte, []int) {
	return file_ethereal_proto_rawDescGZIP(), []int{0}
}

func (x *MarketPrice) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *MarketPrice) GetBidPx() string {
	if x != nil {
		return x.BidPx
	}
	return ""
}

func (x *MarketPrice) GetAskPx() string {
	if x != nil {
		return x.AskPx
	}
	return ""
}

func (x *MarketPrice) GetBidAmt() string {
	if x != nil {
		return x.BidAmt
	}
	return ""
}

func (x *MarketPrice) GetAskAmt() string {
	if x != nil {
		return x.AskAmt
	}
	return ""
}

func (x *MarketPrice) GetMarkPx() string {
	if x != nil {
		return x.MarkPx
	}
	return ""
}

func (x *MarketPrice) GetMark24HPx() string {
	if x != nil {
		return x.Mark24HPx
	}
	return ""
}

type L2Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S             string                 `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	T             int64                  `protobuf:"varint,2,opt,name=t,proto3" json:"t,omitempty"`
	Pt            int64                  `protobuf:"varint,3,opt,name=pt,proto3" json:"pt,omitempty"`
	BidAmt        string                 `protobuf:"bytes,4,opt,name=bid_amt,json=bidAmt,proto3" json:"bid_amt,omitempty"`
	AskAmt        string                 `protobuf:"bytes,5,opt,name=ask_amt,json=askAmt,proto3" json:"ask_amt,omitempty"`
	A             []*structpb.ListValue  `protobuf:"bytes,6,rep,name=a,proto3" json:"a,omitempty"`
	B             []*structpb.ListValue  `protobuf:"bytes,7,rep,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2Book) Reset() {
	*x = L2Book{}
	mi := &file_ethereal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2Book) ProtoMessage() {}

func (x *L2Book) ProtoReflect() protoreflect.Message {
	mi := &file_ethereal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2Book.ProtoReflect.Descriptor instead.
func (*L2Book) Descriptor() ([]byte, []int) {
	return file_ethereal_proto_rawDescGZIP(), []int{1}
}

func (x *L2Book) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *L2Book) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *L2Book) GetPt() int64 {
	if x != nil {
		return x.Pt
	}
	return 0
}

func (x *L2Book) GetBidAmt() string {
	if x != nil {
		return x.BidAmt
	}
	return ""
}

func (x *L2Book) GetAskAmt() string {
	if x != nil {
		return x.AskAmt
	}
	return ""
}

func (x *L2Book) GetA() []*structpb.ListValue {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *L2Book) GetB() []*structpb.ListValue {
	if x != nil {
		return x.B
	}
	return nil
}

type EventMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	E     string                 `protobuf:"bytes,1,opt,name=e,proto3" json:"e,omitempty"`
	T     int64                  `protobuf:"varint,2,opt,name=t,proto3" json:"t,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*EventMessage_MarketPrice
	//	*EventMessage_BookDiff
	Data          isEventMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_ethereal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ethereal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_ethereal_proto_rawDescGZIP(), []int{2}
}

func (x *EventMessage) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

func (x *EventMessage) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *EventMessage) GetData() isEventMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EventMessage) GetMarketPrice() *MarketPrice {
	if x != nil {
		if x, ok := x.Data.(*EventMessage_MarketPrice); ok {
			return x.MarketPrice
		}
	}
	return nil
}

func (x *EventMessage) GetBookDiff() *L2Book {
	if x != nil {
		if x, ok := x.Data.(*EventMessage_BookDiff); ok {
			return x.BookDiff
		}
	}
	return nil
}

type isEventMessage_Data interface {
	isEventMessage_Data()
}

type EventMessage_MarketPrice struct {
	MarketPrice *MarketPrice `protobuf:"bytes,6,opt,name=market_price,json=marketPrice,proto3,oneof"`
}

type EventMessage_BookDiff struct {
	BookDiff *L2Book `protobuf:"bytes,7,opt,name=book_diff,json=bookDiff,proto3,oneof"`
}

func (*EventMessage_MarketPrice) isEventMessage_Data() {}

func (*EventMessage_BookDiff) isEventMessage_Data() {}

var File_ethereal_proto protoreflect.FileDescriptor

const file_ethereal_proto_rawDesc = "" +
	"\n" +
	"\x0eethereal.proto\x12\x0frim.v1.ethereal\x1a\x1cgoogle/protobuf/struct.proto\"\xb3\x01\n" +
	"\vMarketPrice\x12\f\n" +
	"\x01s\x18\x01 \x01(\tR\x01s\x12\x15\n" +
	"\x06bid_px\x18\x02 \x01(\tR\x05bidPx\x12\x15\n" +
	"\x06ask_px\x18\x03 \x01(\tR\x05askPx\x12\x17\n" +
	"\abid_amt\x18\x04 \x01(\tR\x06bidAmt\x12\x17\n" +
	"\aask_amt\x18\x05 \x01(\tR\x06askAmt\x12\x17\n" +
	"\amark_px\x18\x06 \x01(\tR\x06markPx\x12\x1d\n" +
	"\n" +
	"mark24h_px\x18\a \x01(\tR\tmark24hPx\"\xba\x01\n" +
	"\x06L2Book\x12\f\n" +
	"\x01s\x18\x01 \x01(\tR\x01s\x12\f\n" +
	"\x01t\x18\x02 \x01(\x03R\x01t\x12\x0e\n" +
	"\x02pt\x18\x03 \x01(\x03R\x02pt\x12\x17\n" +
	"\abid_amt\x18\x04 \x01(\tR\x06bidAmt\x12\x17\n" +
	"\aask_amt\x18\x05 \x01(\tR\x06askAmt\x12(\n" +
	"\x01a\x18\x06 \x03(\v2\x1a.google.protobuf.ListValueR\x01a\x12(\n" +
	"\x01b\x18\a \x03(\v2\x1a.google.protobuf.ListValueR\x01b\"\xad\x01\n" +
	"\fEventMessage\x12\f\n" +
	"\x01e\x18\x01 \x01(\tR\x01e\x12\f\n" +
	"\x01t\x18\x02 \x01(\x03R\x01t\x12A\n" +
	"\fmarket_price\x18\x06 \x01(\v2\x1c.rim.v1.ethereal.MarketPriceH\x00R\vmarketPrice\x126\n" +
	"\tbook_diff\x18\a \x01(\v2\x17.rim.v1.ethereal.L2BookH\x00R\bbookDiffB\x06\n" +
	"\x04dataB)Z'/ethereal-go/websocket_client;wssClientb\x06proto3"

var (
	file_ethereal_proto_rawDescOnce sync.Once
	file_ethereal_proto_rawDescData []byte
)

func file_ethereal_proto_rawDescGZIP() []byte {
	file_ethereal_proto_rawDescOnce.Do(func() {
		file_ethereal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ethereal_proto_rawDesc), len(file_ethereal_proto_rawDesc)))
	})
	return file_ethereal_proto_rawDescData
}

var file_ethereal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ethereal_proto_goTypes = []any{
	(*MarketPrice)(nil),        // 0: rim.v1.ethereal.MarketPrice
	(*L2Book)(nil),             // 1: rim.v1.ethereal.L2Book
	(*EventMessage)(nil),       // 2: rim.v1.ethereal.EventMessage
	(*structpb.ListValue)(nil), // 3: google.protobuf.ListValue
}
var file_ethereal_proto_depIdxs = []int32{
	3, // 0: rim.v1.ethereal.L2Book.a:type_name -> google.protobuf.ListValue
	3, // 1: rim.v1.ethereal.L2Book.b:type_name -> google.protobuf.ListValue
	0, // 2: rim.v1.ethereal.EventMessage.market_price:type_name -> rim.v1.ethereal.MarketPrice
	1, // 3: rim.v1.ethereal.EventMessage.book_diff:type_name -> rim.v1.ethereal.L2Book
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ethereal_proto_init() }
func file_ethereal_proto_init() {
	if File_ethereal_proto != nil {
		return
	}
	file_ethereal_proto_msgTypes[2].OneofWrappers = []any{
		(*EventMessage_MarketPrice)(nil),
		(*EventMessage_BookDiff)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ethereal_proto_rawDesc), len(file_ethereal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ethereal_proto_goTypes,
		DependencyIndexes: file_ethereal_proto_depIdxs,
		MessageInfos:      file_ethereal_proto_msgTypes,
	}.Build()
	File_ethereal_proto = out.File
	file_ethereal_proto_goTypes = nil
	file_ethereal_proto_depIdxs = nil
}
