// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: ethereal.proto

package etherealpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiffLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffLevel) Reset() {
	*x = DiffLevel{}
	mi := &file_ethereal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffLevel) ProtoMessage() {}

func (x *DiffLevel) ProtoReflect() protoreflect.Message {
	mi := &file_ethereal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffLevel.ProtoReflect.Descriptor instead.
func (*DiffLevel) Descriptor() ([]byte, []int) {
	return file_ethereal_proto_rawDescGZIP(), []int{0}
}

func (x *DiffLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *DiffLevel) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type BookDiff struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Timestamp         int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PreviousTimestamp int64                  `protobuf:"varint,3,opt,name=previous_timestamp,json=previousTimestamp,proto3" json:"previous_timestamp,omitempty"`
	Asks              []*DiffLevel           `protobuf:"bytes,4,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids              []*DiffLevel           `protobuf:"bytes,5,rep,name=bids,proto3" json:"bids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BookDiff) Reset() {
	*x = BookDiff{}
	mi := &file_ethereal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDiff) ProtoMessage() {}

func (x *BookDiff) ProtoReflect() protoreflect.Message {
	mi := &file_ethereal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDiff.ProtoReflect.Descriptor instead.
func (*BookDiff) Descriptor() ([]byte, []int) {
	return file_ethereal_proto_rawDescGZIP(), []int{1}
}

func (x *BookDiff) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *BookDiff) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BookDiff) GetPreviousTimestamp() int64 {
	if x != nil {
		return x.PreviousTimestamp
	}
	return 0
}

func (x *BookDiff) GetAsks() []*DiffLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *BookDiff) GetBids() []*DiffLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

var File_ethereal_proto protoreflect.FileDescriptor

const file_ethereal_proto_rawDesc = "" +
	"\n" +
	"\x0eethereal.proto\x12\bethereal\"5\n" +
	"\tDiffLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\"\xc8\x01\n" +
	"\bBookDiff\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12-\n" +
	"\x12previous_timestamp\x18\x03 \x01(\x03R\x11previousTimestamp\x12'\n" +
	"\x04asks\x18\x04 \x03(\v2\x13.ethereal.DiffLevelR\x04asks\x12'\n" +
	"\x04bids\x18\x05 \x03(\v2\x13.ethereal.DiffLevelR\x04bidsB0Z.github.com/qiwi1272/ethereal-go/_pb;etherealpbb\x06proto3"

var (
	file_ethereal_proto_rawDescOnce sync.Once
	file_ethereal_proto_rawDescData []byte
)

func file_ethereal_proto_rawDescGZIP() []byte {
	file_ethereal_proto_rawDescOnce.Do(func() {
		file_ethereal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ethereal_proto_rawDesc), len(file_ethereal_proto_rawDesc)))
	})
	return file_ethereal_proto_rawDescData
}

var file_ethereal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ethereal_proto_goTypes = []any{
	(*DiffLevel)(nil), // 0: ethereal.DiffLevel
	(*BookDiff)(nil),  // 1: ethereal.BookDiff
}
var file_ethereal_proto_depIdxs = []int32{
	0, // 0: ethereal.BookDiff.asks:type_name -> ethereal.DiffLevel
	0, // 1: ethereal.BookDiff.bids:type_name -> ethereal.DiffLevel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ethereal_proto_init() }
func file_ethereal_proto_init() {
	if File_ethereal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ethereal_proto_rawDesc), len(file_ethereal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ethereal_proto_goTypes,
		DependencyIndexes: file_ethereal_proto_depIdxs,
		MessageInfos:      file_ethereal_proto_msgTypes,
	}.Build()
	File_ethereal_proto = out.File
	file_ethereal_proto_goTypes = nil
	file_ethereal_proto_depIdxs = nil
}
