// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: ethereal.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_ethereal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_ethereal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_ethereal_proto_rawDescGZIP(), []int{0}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type BookDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bids          []*PriceLevel          `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*PriceLevel          `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	B             []*PriceLevel          `protobuf:"bytes,3,rep,name=b,proto3" json:"b,omitempty"`
	A             []*PriceLevel          `protobuf:"bytes,4,rep,name=a,proto3" json:"a,omitempty"`
	Symbol        string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookDiff) Reset() {
	*x = BookDiff{}
	mi := &file_ethereal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDiff) ProtoMessage() {}

func (x *BookDiff) ProtoReflect() protoreflect.Message {
	mi := &file_ethereal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDiff.ProtoReflect.Descriptor instead.
func (*BookDiff) Descriptor() ([]byte, []int) {
	return file_ethereal_proto_rawDescGZIP(), []int{1}
}

func (x *BookDiff) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *BookDiff) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *BookDiff) GetB() []*PriceLevel {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *BookDiff) GetA() []*PriceLevel {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *BookDiff) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

var File_ethereal_proto protoreflect.FileDescriptor

const file_ethereal_proto_rawDesc = "" +
	"\n" +
	"\x0eethereal.proto\x12\bspoke.v1\"6\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\"\xbe\x01\n" +
	"\bBookDiff\x12(\n" +
	"\x04bids\x18\x01 \x03(\v2\x14.spoke.v1.PriceLevelR\x04bids\x12(\n" +
	"\x04asks\x18\x02 \x03(\v2\x14.spoke.v1.PriceLevelR\x04asks\x12\"\n" +
	"\x01b\x18\x03 \x03(\v2\x14.spoke.v1.PriceLevelR\x01b\x12\"\n" +
	"\x01a\x18\x04 \x03(\v2\x14.spoke.v1.PriceLevelR\x01a\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbolB\x14Z\x12ethereal-go/_pb;pbb\x06proto3"

var (
	file_ethereal_proto_rawDescOnce sync.Once
	file_ethereal_proto_rawDescData []byte
)

func file_ethereal_proto_rawDescGZIP() []byte {
	file_ethereal_proto_rawDescOnce.Do(func() {
		file_ethereal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ethereal_proto_rawDesc), len(file_ethereal_proto_rawDesc)))
	})
	return file_ethereal_proto_rawDescData
}

var file_ethereal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ethereal_proto_goTypes = []any{
	(*PriceLevel)(nil), // 0: spoke.v1.PriceLevel
	(*BookDiff)(nil),   // 1: spoke.v1.BookDiff
}
var file_ethereal_proto_depIdxs = []int32{
	0, // 0: spoke.v1.BookDiff.bids:type_name -> spoke.v1.PriceLevel
	0, // 1: spoke.v1.BookDiff.asks:type_name -> spoke.v1.PriceLevel
	0, // 2: spoke.v1.BookDiff.b:type_name -> spoke.v1.PriceLevel
	0, // 3: spoke.v1.BookDiff.a:type_name -> spoke.v1.PriceLevel
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ethereal_proto_init() }
func file_ethereal_proto_init() {
	if File_ethereal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ethereal_proto_rawDesc), len(file_ethereal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ethereal_proto_goTypes,
		DependencyIndexes: file_ethereal_proto_depIdxs,
		MessageInfos:      file_ethereal_proto_msgTypes,
	}.Build()
	File_ethereal_proto = out.File
	file_ethereal_proto_goTypes = nil
	file_ethereal_proto_depIdxs = nil
}
